In [1]:
import pandas as pd 
import csv

In [2]:
df = pd.read_csv('Opioid County Deaths over Time - Sheet1.csv')

In [3]:
df[df.County == 'Alameda'].sort_values('Year', ascending=True)

#Data check

      County   Rate  95% LCL 95% UCL  Count       Stability  Year
579  Alameda   1.97     1.36    2.81     33  Rate is stable  2012
556  Alameda   2.48     1.80    3.38     44  Rate is stable  2013
530  Alameda   2.91     2.16    3.87     51  Rate is stable  2014
480  Alameda   3.83     2.97    4.89     68  Rate is stable  2015
535  Alameda   2.81     2.10    3.73     51  Rate is stable  2016
577  Alameda   2.03     1.43    2.83     37  Rate is stable  2017
522  Alameda   3.10     2.33    4.07     56  Rate is stable  2018
385  Alameda   5.75     4.69       7    103  Rate is stable  2019
281  Alameda   8.09     6.81    9.57    144  Rate is stable  2020
199  Alameda  11.37     9.84   13.09    203  Rate is stable  2021
167  Alameda  13.24    11.56   15.13    229  Rate is stable  2022

In [8]:
horizontal_pivot = df.pivot_table(index='County', columns='Year', values='Rate')
print(horizontal_pivot)

#pivot vertial data into horizontal data by year

Year              2012   2013   2014   2015   2016   2017   2018   2019  \
County
Alameda           1.97   2.48   2.91   3.83   2.81   2.03   3.10   5.75
Alpine            0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
Amador           13.98   6.26  14.75   3.75  15.61   2.71   2.90   7.82
Butte             9.01   4.63   5.79   7.48   7.08   7.57   6.55   5.83
Calaveras        15.38   4.61   1.76  17.97  16.50   0.86   9.71   7.79
California        4.30   4.79   4.92   4.79   4.87   5.22   5.82   7.90
Colusa            6.14  10.85   0.00   0.00   6.80   0.00   0.00  15.65
Contra Costa      3.77   3.58   4.52   4.19   4.38   4.35   6.82   7.86
Del Norte         4.58  21.40   7.25  10.21  11.01  12.56   0.00   4.67
El Dorado         3.24   1.22   3.30   4.04   6.15   2.38   4.14   5.80
Fresno            4.79   5.37   7.63   6.80   7.28   4.58   3.52   4.86
Glenn             0.00   6.91  11.17   2.59   3.39   0.00   4.71   3.31
Humboldt         15.80  13.42  19.84  18.05  22.35  21.03  11.17  19.05
Imperial          2.98   6.75   6.77  12.65   7.34   4.57  10.07   7.02
Inyo              0.00  15.52   0.00   0.00  22.91   3.19  17.77  14.47
Kern              5.22   5.39   8.33   8.60   5.99   8.45  10.46  12.79
Kings             3.67   5.94   8.40   3.42   3.98   4.52   2.76   1.06
Lake             22.32  29.81  25.39  26.92  12.42  17.02  22.70  32.46
Lassen           13.46  14.67  13.34  10.51  19.86  13.91  11.90  23.47
Los Angeles       2.25   2.75   2.69   2.65   3.21   4.05   4.57   6.70
Madera           11.56   8.58   6.77   5.71   6.48   3.75   3.98   8.33
Marin             5.46   3.91   1.52   1.50   6.34   6.59   3.46   9.27
Mariposa          7.91   4.05  32.86   4.56   2.22   5.51   0.00  23.40
Mendocino         2.85  10.61  16.96  15.05  17.34  19.34  13.70  21.13
Merced            3.05   6.52   5.89   8.35   9.82   4.67   7.30   7.74
Modoc            43.66  12.84  14.20   7.16   0.00  23.58   0.00   0.00
Mono              0.00   0.00   0.00   0.00   6.89   0.00   0.00   0.00
Monterey          5.91   6.09   3.48   3.23   2.42   1.65   1.73   4.46
Napa              0.44   3.58   3.75   5.87   1.64   3.15   3.97   2.29
Nevada            4.42   9.17   5.07   4.07   9.85   5.50   6.28  10.45
Orange            6.53   7.49   7.56   7.39   8.47   7.50   7.46   8.13
Placer            2.29   3.41   2.14   3.94   3.75   4.79   1.94   7.39
Plumas           22.80  31.18  20.52  31.30   0.00   2.00  18.11  11.77
Riverside         5.32   5.53   6.18   5.55   4.63   5.67   5.74   9.77
Sacramento        4.17   7.16   3.85   2.44   3.40   3.75   4.64   7.39
San Benito        4.63   8.54   4.60   5.23   3.85   9.47   3.22   7.98
San Bernardino    2.77   2.65   2.66   1.74   1.67   2.65   4.77   6.10
San Diego         7.83   7.63   6.95   6.94   7.10   7.81   7.39   8.92
San Francisco     5.95   7.66   8.57   9.56   9.20   9.62  15.01  26.96
San Joaquin       5.80   8.99   9.61   6.12   6.80   9.18   3.47   5.30
San Luis Obispo   6.35   8.63   6.58   9.85   6.96   7.76   4.29   8.13
San Mateo         2.15   2.38   2.26   2.97   2.54   4.75   4.83   7.87
Santa Barbara     3.13   4.55   5.23   7.70   7.38   7.48   7.09   5.54
Santa Clara       2.27   2.68   2.80   3.17   3.24   3.19   2.83   4.12
Santa Cruz        9.66   9.48  15.53  10.68  12.32   6.59   8.49  10.47
Shasta           13.96  11.85  11.91   8.97   8.64  14.06   5.43  11.11
Sierra            0.00   0.00   0.00   0.00   0.00   0.00   0.00   0.00
Siskiyou         14.37   0.00   6.63  17.31  21.98   9.97   3.62   5.98
Solano            0.58   2.67   6.51   4.68   3.30   2.46   4.02   7.32
Sonoma            5.09   2.35   5.73   6.79   4.83   5.99   9.23  13.09
Stanislaus        2.48   3.17   2.98   5.37   2.56   3.38   5.96   8.57
Sutter            4.91   8.31   3.22   0.00   4.36   2.05   8.72   2.50
Tehama            3.99   3.07   2.18   2.87   3.30   0.00   3.52   1.02
Trinity           3.49  23.68   3.89   6.95  13.40   4.33   7.47  19.65
Tulare            2.06   4.29   3.96   2.50   3.01   2.59   1.73   2.52
Tuolumne         13.99   8.54  13.69  27.68  11.35   9.47   2.52   1.59
Ventura          10.75   7.59   7.34   5.64   5.01   9.80  11.14  10.05
Yolo              3.86   4.25   4.63   6.47   4.29   3.19   2.21   3.91
Yuba              0.00   0.00   4.46   6.14   8.08  13.15   5.36  10.82

Year              2020   2021   2022
County
Alameda           8.09  11.37  13.24
Alpine            0.00  51.55   0.00
Amador           13.07  19.73  14.55
Butte            11.54  28.80  33.23
Calaveras         7.00  17.34  15.14
California       13.54  18.03  18.66
Colusa           14.72   2.98  19.05
Contra Costa     12.61  16.14  15.91
Del Norte         9.01  16.98  74.20
El Dorado        11.72  20.27  20.11
Fresno            7.01   8.85  13.30
Glenn            14.87  14.25  22.76
Humboldt         18.34  36.53  61.66
Imperial         19.07   9.59  13.56
Inyo             22.03  41.59  22.55
Kern             24.32  31.02  34.22
Kings             7.36  10.04  11.29
Lake             26.11  49.84  55.46
Lassen           18.13  13.82  37.16
Los Angeles      12.40  15.35  16.53
Madera            4.87  12.38   6.79
Marin            14.06  18.16  15.79
Mariposa          3.87  19.69   8.27
Mendocino        25.84  54.70  54.91
Merced            9.98   9.58  13.84
Modoc             0.00  23.44  12.51
Mono              0.00   0.00   8.54
Monterey          5.85   5.61   6.82
Napa              5.20  10.44  15.60
Nevada           34.09  32.02  18.03
Orange           15.45  24.07  20.62
Placer           12.22  12.91  13.63
Plumas            6.28  11.05  18.66
Riverside        16.05  20.37  23.56
Sacramento        6.81  14.29  14.90
San Benito        6.33  15.43  18.73
San Bernardino   12.95  16.05  17.36
San Diego        15.14  22.45  22.83
San Francisco    44.51  41.99  33.65
San Joaquin      11.10  18.66  14.45
San Luis Obispo  20.56  27.88  33.92
San Mateo        10.06  11.37  10.65
Santa Barbara     3.54  12.79  10.51
Santa Clara       7.09   7.73   8.60
Santa Cruz        9.65  15.59  28.92
Shasta           16.25  30.89  29.89
Sierra            0.00   0.00   0.00
Siskiyou         19.37  16.82  53.33
Solano            8.71  12.91  17.43
Sonoma           23.69  25.57  20.34
Stanislaus       13.50  19.63  24.52
Sutter           10.35  20.87  22.68
Tehama            3.38  12.84  34.34
Trinity           0.00  53.52  11.66
Tulare            8.22  12.87  12.30
Tuolumne          3.48  23.16  21.71
Ventura          17.07  26.06  24.42
Yolo              4.04   2.15  12.22
Yuba             10.64  23.24  27.91